Quieten pyflakes.
Fixes:

    ./lib/cli.py:409: redefinition of unused 'device' from line 401
    ./tests/tools.py:177: redefinition of unused 'fork_isolation' from line 125