lib.cli: improve --override-xmp error handling.
Before:

    $ scanhelper --override-xmp foo
    Traceback (most recent call last):
      File ".../scanhelper", line 25, in <module>
        main()
      File ".../lib/cli.py", line 525, in main
        options = parser.parse_args()
                  ^^^^^^^^^^^^^^^^^^^
      File ".../lib/cli.py", line 242, in parse_args
        result.override_xmp = dict(
                              ^^^^^
    ValueError: dictionary update sequence element #0 has length 1; 2 is required

After:

    $ scanhelper --override-xmp foo
    usage: scanhelper [-d DEVICE] [-L] [--format {pnm,tiff,png}]
                      ...
    scanhelper: error: argument --override-xmp: invalid KEY=VALUE value: 'foo'